name: WanderLust
favicon: null
layout_spectrum: 0.91195
typography_spectrum: 0.152027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D0C8B8'
    - '#784008'
    - '#68A8B0'
    - '#D09828'
    - '#E0B048'
  brandStrength: 0.5625
  lightness: 0.474099
  saturation: 0.1875
  rhythmicContrast: 0.54054
purpose: []
