analytics: {}
color:
  brandColors:
    - '#D0C8B8'
    - '#784008'
    - '#68A8B0'
    - '#D09828'
    - '#E0B048'
  brandStrength: 0.427927
  lightness: 0.474099
  rhythmicContrast: 0.54054
  saturation: 0.661036
cta: {}
layout_spectrum: 0.906531
name: WanderLust
opengraph: {}
purpose: []
typography_spectrum: 0.152027
